version: 1.0.{build}
branches:
  only:
    - node_12_changes
max_jobs: 1

# Build worker image (VM template)
image:
#  - Visual Studio 2019
  - Ubuntu
  - macOS

clone_depth: 5                      # clone entire repository history if not defined

for:
-
  matrix:
    only:
      - image: Ubuntu

  before_build:
  - sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd

# to run your custom scripts instead of automatic MSBuild
build_script:
  - yarn install

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:

before_test:

# to run your custom scripts instead of automatic tests
test_script:
  - node examples/example.js

# scripts to run after tests
after_test:

deploy: off
