version: 1.0.{build}
branches:
  only:
    - node_12_changes
max_jobs: 1

# Build worker image (VM template)
image:
  - Ubuntu
  - macOS
  - Visual Studio 2019

clone_depth: 5                      # clone entire repository history if not defined

for:
-
  matrix:
    only:
      - image: Ubuntu

  before_build:
  - sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd
-
  matrix:
    only:
      - image: macOS

  before_build:
  - npm install -g yarn


environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"
    - nodejs_version: "13"

install:
  - nvm use $env:nodejs_version

# to run your custom scripts instead of automatic MSBuild
build_script:
  - yarn install

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:

test: off
deploy: off
